FROM  python:3.9-slim

WORKDIR /usr/src/backend/app
COPY ./backend/app/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /usr/src/backend/app/requirements.txt
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

COPY ./backend/ .
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "5001"]
