import Head from "next/head";
import Link from "next/link";

import styles from "@/styles/Home.module.css";

import Text from "@/components/text/Text";
import Button from "@/components/button/Button";
import ButtonArea from "@/components/buttonArea/ButtonArea";
import Rank from "@/components/rank/Rank";
import { useState, useEffect } from "react";
import { Layout } from "@/components/Layout";

export default function Home() {
    const [ranking, setRanking] = useState([]);
    useEffect(() => {
        const getRanking = async () => {
            const res = await fetch("http://localhost:3000/api/ranking").then((res) => res.json());
            setRanking(res);
        };
        getRanking();
    }, []);
    return (
        <>
            <Head>
                <title>エモちゃれ!! - You Are My Corn</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Text text="この「キモチ」、うまくあのコにつたえたい。" />
                <ButtonArea>
                    {/* TODO: あそびかたをひょうじするFloatwindow */}
                    <Button text="あそびかた" />
                    <Link href="/play">
                        <Button text="GAME START" />
                    </Link>
                </ButtonArea>
                <Text text="★ スコアランキング ★" />
                <Rank ranking={ranking} />
            </main>
        </>
    );
}

Home.getLayout = function getLayout(page: any) {
    return <Layout>{page}</Layout>;
};
