import Head from "next/head";
import Link from "next/link";

import { useEffect, useState } from "react";

import styles from "@/styles/Home.module.css";

import { Layout } from "@/components/Layout";
import Loading from "@/components/Loading";
import Button from "@/components/button/Button";
import ButtonArea from "@/components/buttonArea/ButtonArea";
import FloatingWindow from "@/components/floatingWindow/FloatingWindow";
import Rank from "@/components/rank/Rank";
import Text from "@/components/text/Text";
import Config from "@/lib/config";

export default function Home() {
    const [ranking, setRanking] = useState([]);
    const [isOpen, setIsOpen] = useState(false);
    const [isLoaded, setIsLoaded] = useState(false);
    useEffect(() => {
        const getRanking = async () => {
            const res = await fetch(Config.apiUrl + "api/ranking").then((res) => res.json());
            setRanking(res);
            setIsLoaded(true);
        };
        getRanking();
    }, []);
    const toggle = () => {
        setIsOpen(!isOpen);
    };

    return (
        <>
            <Head>
                <title>エモちゃれ!! - You Are My Corn</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Text text="この「キモチ」、うまくあのコにつたえたい。" />
                <ButtonArea>
                    <Button text="あそびかた" onClickFunc={toggle} />
                    {isOpen && <FloatingWindow setIsOpen={setIsOpen} />}
                    <Link href="/play">
                        <Button text="GAME START" />
                    </Link>
                </ButtonArea>
                <Text text="★ スコアランキング ★" />
                {!isLoaded ? <Loading text="けっかをロードちゅう" /> : <Rank ranking={ranking} />}
            </main>
        </>
    );
}

Home.getLayout = function getLayout(page: any) {
    return <Layout>{page}</Layout>;
};
