import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import Button from "@/components/button/Button";
import ButtonArea from "@/components/buttonArea/ButtonArea";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header />
                <ButtonArea>
                    <Button text="GAME START" />
                </ButtonArea>
            </main>
        </>
    );
}
