import Head from "next/head";
import Image from "next/image";

import { useState, useEffect } from "react";

import styles from "@/styles/play.module.css";

import { genreDict } from "@/lib/data";
import { conditionsDataAtom } from "@/lib/jotai";

import { useSetAtom } from "jotai";

import Text from "@/components/text/Text";
import Box from "@/components/box/Box";
import SpeechBuble from "@/components/speechBuble/SpeechBuble";
import { MaxWidthLayout } from "@/components/MaxWidthLayout";
import Timer from "@/components/timer/Timer";

export default function Play() {
    const [genre, setGenre] = useState<string>("");
    const [requiredWord, setRequiredWord] = useState<string[]>([]);
    const [forbiddenWord, setForbiddenWord] = useState<string[]>([]);
    const [isLimit, setIsLimit] = useState<boolean>(false);
    const setPlayData = useSetAtom(conditionsDataAtom);
    const time = new Date();
    const playTime = 120;
    time.setSeconds(time.getSeconds() + playTime);

    useEffect(() => {
        const fetchStart = async () => {
            await fetch("http://localhost:3000/api/start").then((res) => {
                res.json().then((data) => {
                    setGenre(genreDict[data.category]);
                    setRequiredWord(data.requiredWords);
                    setForbiddenWord(data.forbiddenWords);
                    setPlayData(data);
                });
            });
        };
        fetchStart();
    }, []);

    return (
        <>
            <Head>
                <title>エモちゃれ!! - You Are My Corn</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.themeArea}>
                <Text text="あなたがめざすかんじょうは..." color="#ff527B" />
                <h2 className={styles.theme}>{genre}</h2>
            </div>
            <div className={styles.boxArea}>
                <Box heading="ぜったいにつかうワード" words={requiredWord} />
                <Box heading="きんしワード" words={forbiddenWord} />
            </div>
            <Timer expiryTimestamp={time} onExpireFunc={setIsLimit} />
            <div className={styles.textArea}>
                <Image className={styles.cornLogo} src="/morokoshi_boy.svg" height={300} width={300} alt="logo" />
                <SpeechBuble isLimit={isLimit} />
            </div>
        </>
    );
}

Play.getLayout = function getLayout(page: any) {
    return <MaxWidthLayout>{page}</MaxWidthLayout>;
};
