import Head from "next/head";
import Link from "next/link";

import Header from "@/components/header/Header";
import Button from "@/components/button/Button";
import ButtonArea from "@/components/buttonArea/ButtonArea";

export default function Play() {
    const onClick = () => {
        function fetchback() {
            const data = fetch("http://localhost:5001");
            console.log(data);
        }
        fetchback();
    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <button
                onClick={() => {
                    onClick();
                }}
            >
                click
            </button>
        </>
    );
}
